//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCompliance.DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CallComplianceModelContainer : DbContext
    {
        public CallComplianceModelContainer()
            : base("name=CallComplianceModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int AddExceptionsPhoneNumber(string phoneNumber, Nullable<System.DateTime> dateTimeExceptionGranted, string requestorId, string requestorName, string requestorDepartment, Nullable<int> exceptionReasonId, Nullable<int> syStudentId, string nameAssigned, string notes, Nullable<bool> isStudent)
        {
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var dateTimeExceptionGrantedParameter = dateTimeExceptionGranted.HasValue ?
                new ObjectParameter("DateTimeExceptionGranted", dateTimeExceptionGranted) :
                new ObjectParameter("DateTimeExceptionGranted", typeof(System.DateTime));
    
            var requestorIdParameter = requestorId != null ?
                new ObjectParameter("RequestorId", requestorId) :
                new ObjectParameter("RequestorId", typeof(string));
    
            var requestorNameParameter = requestorName != null ?
                new ObjectParameter("RequestorName", requestorName) :
                new ObjectParameter("RequestorName", typeof(string));
    
            var requestorDepartmentParameter = requestorDepartment != null ?
                new ObjectParameter("RequestorDepartment", requestorDepartment) :
                new ObjectParameter("RequestorDepartment", typeof(string));
    
            var exceptionReasonIdParameter = exceptionReasonId.HasValue ?
                new ObjectParameter("ExceptionReasonId", exceptionReasonId) :
                new ObjectParameter("ExceptionReasonId", typeof(int));
    
            var syStudentIdParameter = syStudentId.HasValue ?
                new ObjectParameter("SyStudentId", syStudentId) :
                new ObjectParameter("SyStudentId", typeof(int));
    
            var nameAssignedParameter = nameAssigned != null ?
                new ObjectParameter("NameAssigned", nameAssigned) :
                new ObjectParameter("NameAssigned", typeof(string));
    
            var notesParameter = notes != null ?
                new ObjectParameter("Notes", notes) :
                new ObjectParameter("Notes", typeof(string));
    
            var isStudentParameter = isStudent.HasValue ?
                new ObjectParameter("IsStudent", isStudent) :
                new ObjectParameter("IsStudent", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddExceptionsPhoneNumber", phoneNumberParameter, dateTimeExceptionGrantedParameter, requestorIdParameter, requestorNameParameter, requestorDepartmentParameter, exceptionReasonIdParameter, syStudentIdParameter, nameAssignedParameter, notesParameter, isStudentParameter);
        }
    
        public virtual ObjectResult<cplxExceptionReasonsNames> GetExceptionReasonsNames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cplxExceptionReasonsNames>("GetExceptionReasonsNames");
        }
    
        public virtual ObjectResult<cplxStudentInfoByPhoneNumber> GetStudentInfoByPhoneNumber(string phoneNumber)
        {
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cplxStudentInfoByPhoneNumber>("GetStudentInfoByPhoneNumber", phoneNumberParameter);
        }
    
        public virtual int AddDNCPhoneNumber(string phoneNumber, Nullable<int> dNCListId, string requestorId, string requestorName, string requestorDepartment)
        {
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var dNCListIdParameter = dNCListId.HasValue ?
                new ObjectParameter("DNCListId", dNCListId) :
                new ObjectParameter("DNCListId", typeof(int));
    
            var requestorIdParameter = requestorId != null ?
                new ObjectParameter("RequestorId", requestorId) :
                new ObjectParameter("RequestorId", typeof(string));
    
            var requestorNameParameter = requestorName != null ?
                new ObjectParameter("RequestorName", requestorName) :
                new ObjectParameter("RequestorName", typeof(string));
    
            var requestorDepartmentParameter = requestorDepartment != null ?
                new ObjectParameter("RequestorDepartment", requestorDepartment) :
                new ObjectParameter("RequestorDepartment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddDNCPhoneNumber", phoneNumberParameter, dNCListIdParameter, requestorIdParameter, requestorNameParameter, requestorDepartmentParameter);
        }
    
        public virtual ObjectResult<cplxDNCListsListNames> GetDNCListsListNames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cplxDNCListsListNames>("GetDNCListsListNames");
        }
    
        public virtual int AddCooldownsPhoneNumber(string phoneNumber, Nullable<System.DateTime> dateTimeInitiated, string requestorId, string requestorName, string requestorDepartment, string notes, Nullable<int> syStudentId, string studentName)
        {
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var dateTimeInitiatedParameter = dateTimeInitiated.HasValue ?
                new ObjectParameter("DateTimeInitiated", dateTimeInitiated) :
                new ObjectParameter("DateTimeInitiated", typeof(System.DateTime));
    
            var requestorIdParameter = requestorId != null ?
                new ObjectParameter("RequestorId", requestorId) :
                new ObjectParameter("RequestorId", typeof(string));
    
            var requestorNameParameter = requestorName != null ?
                new ObjectParameter("RequestorName", requestorName) :
                new ObjectParameter("RequestorName", typeof(string));
    
            var requestorDepartmentParameter = requestorDepartment != null ?
                new ObjectParameter("RequestorDepartment", requestorDepartment) :
                new ObjectParameter("RequestorDepartment", typeof(string));
    
            var notesParameter = notes != null ?
                new ObjectParameter("Notes", notes) :
                new ObjectParameter("Notes", typeof(string));
    
            var syStudentIdParameter = syStudentId.HasValue ?
                new ObjectParameter("SyStudentId", syStudentId) :
                new ObjectParameter("SyStudentId", typeof(int));
    
            var studentNameParameter = studentName != null ?
                new ObjectParameter("StudentName", studentName) :
                new ObjectParameter("StudentName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddCooldownsPhoneNumber", phoneNumberParameter, dateTimeInitiatedParameter, requestorIdParameter, requestorNameParameter, requestorDepartmentParameter, notesParameter, syStudentIdParameter, studentNameParameter);
        }
    
        public virtual int AddWhitelistPhoneNumber(string phoneNumber, string requestorId, string requestorName, string requestorDepartment, string notes, Nullable<bool> dNCOverride)
        {
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var requestorIdParameter = requestorId != null ?
                new ObjectParameter("RequestorId", requestorId) :
                new ObjectParameter("RequestorId", typeof(string));
    
            var requestorNameParameter = requestorName != null ?
                new ObjectParameter("RequestorName", requestorName) :
                new ObjectParameter("RequestorName", typeof(string));
    
            var requestorDepartmentParameter = requestorDepartment != null ?
                new ObjectParameter("RequestorDepartment", requestorDepartment) :
                new ObjectParameter("RequestorDepartment", typeof(string));
    
            var notesParameter = notes != null ?
                new ObjectParameter("Notes", notes) :
                new ObjectParameter("Notes", typeof(string));
    
            var dNCOverrideParameter = dNCOverride.HasValue ?
                new ObjectParameter("DNCOverride", dNCOverride) :
                new ObjectParameter("DNCOverride", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddWhitelistPhoneNumber", phoneNumberParameter, requestorIdParameter, requestorNameParameter, requestorDepartmentParameter, notesParameter, dNCOverrideParameter);
        }
    
        public virtual int UpdateDNCListsListName(string oldListName, string newListName)
        {
            var oldListNameParameter = oldListName != null ?
                new ObjectParameter("OldListName", oldListName) :
                new ObjectParameter("OldListName", typeof(string));
    
            var newListNameParameter = newListName != null ?
                new ObjectParameter("NewListName", newListName) :
                new ObjectParameter("NewListName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateDNCListsListName", oldListNameParameter, newListNameParameter);
        }
    
        public virtual int UpdateExceptionReasonsName(string oldReasonName, string newReasonName)
        {
            var oldReasonNameParameter = oldReasonName != null ?
                new ObjectParameter("OldReasonName", oldReasonName) :
                new ObjectParameter("OldReasonName", typeof(string));
    
            var newReasonNameParameter = newReasonName != null ?
                new ObjectParameter("NewReasonName", newReasonName) :
                new ObjectParameter("NewReasonName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateExceptionReasonsName", oldReasonNameParameter, newReasonNameParameter);
        }
    
        public virtual int UpdateParametersValue(string parameterName, Nullable<int> parameterValue, string modifiedBy)
        {
            var parameterNameParameter = parameterName != null ?
                new ObjectParameter("ParameterName", parameterName) :
                new ObjectParameter("ParameterName", typeof(string));
    
            var parameterValueParameter = parameterValue.HasValue ?
                new ObjectParameter("ParameterValue", parameterValue) :
                new ObjectParameter("ParameterValue", typeof(int));
    
            var modifiedByParameter = modifiedBy != null ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateParametersValue", parameterNameParameter, parameterValueParameter, modifiedByParameter);
        }
    
        public virtual ObjectResult<cplxParametersValues> GetParametersValues()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cplxParametersValues>("GetParametersValues");
        }
    
        public virtual ObjectResult<cplxTableNameWherePhoneNumberIsLocated> GetTableNameWherePhoneNumberIsLocated(string phoneNumber)
        {
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cplxTableNameWherePhoneNumberIsLocated>("GetTableNameWherePhoneNumberIsLocated", phoneNumberParameter);
        }
    }
}
