//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCompliance.DAL.Models
{
    using System;
    
    public partial class cplxCallComplianceReports
    {
        public string ReportName { get; set; }
    }
}
