//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCompliance.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumberUnBlock
    {
        public int Id { get; set; }
        public string PhoneNumber { get; set; }
        public int ReasonOverrideId { get; set; }
        public int StudentTypeId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string Notes { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
